baseURL = 'https://akshatjme.github.io/'
languageCode = 'en-us'
title = 'Akshat Blogs'

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  description = "A minimal, elegant blog about writing, creativity and coding"
  author = "Akshat Jain"
  font = "Quicksand"
  enableDarkModeToggle = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 1
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 2


[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP", "ROBOTS"]
  section = ["HTML", "RSS"]

[sitemap]
  changefreq = 'weekly'
  priority = 0.5
